# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

source 'https://github.com/oititec/ios-artifactory-beta.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, min_ios_version_supported
prepare_react_native_project!

def __apply_Xcode_14_3_RC_post_install_workaround(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      current_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      minimum_target = min_ios_version_supported
      if current_target.to_f < minimum_target.to_f
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_target
      end
    end
  end
end

def __apply_Xcode_15_unary_binary_function_fix(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION'
    end
  end
end

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'RnLiveness3dExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'RnLiveness3dExampleTests' do
    inherit! :complete
  end

  pod 'OILiveness3D_FT', git: 'https://github.com/oititec/ios-liveness3d-ft.git', branch: 'feature/29846'
  pod 'OILiveness3D', git: 'https://github.com/oititec/ios-liveness-3d.git', branch: 'feature/29846-facetec-update'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Xcode 15+: evita "Internal inconsistency error: never received target ended message"
    installer.pods_project.root_object.attributes['BuildIndependentTargetsInParallel'] = '0'

    __apply_Xcode_14_3_RC_post_install_workaround(installer)
    __apply_Xcode_15_unary_binary_function_fix(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
      end

      if target.name == 'oiti-rn-liveness3d' || target.name.start_with?('oiti-rn-liveness3d/')
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'

          next unless target.name.end_with?('/Swift')

          config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)']
          flags = config.build_settings['OTHER_SWIFT_FLAGS']
          flags = [flags] unless flags.is_a?(Array)
          flags.reject! { |f| f.include?('import-underlying-module') || f.include?('fmodule-map-file') }
          flags << '-DRCT_NEW_ARCH_ENABLED' unless flags.any? { |f| f.include?('RCT_NEW_ARCH_ENABLED') }
          config.build_settings['OTHER_SWIFT_FLAGS'] = flags
        end
      end

      next unless target.name == 'fmt'

      target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      end
    end
  end
end
