export type TextsType = {
  READY_HEADER_1?: string;
  READY_HEADER_2?: string;
  READY_MESSAGE_1?: string;
  READY_MESSAGE_2?: string;
  READY_BUTTON?: string;

  /* Retry Screen */
  RETRY_HEADER?: string;
  RETRY_SUBHEADER?: string;
  RETRY_YOUR_PICTURE?: string;
  RETRY_IDEAL_PICTURE?: string;
  RETRY_MESSAGE_SMILE?: string;
  RETRY_MESSAGE_LIGHTING?: string;
  RETRY_MESSAGE_CONTRAST?: string;
  RETRY_BUTTON?: string;

  /* Result Screen */
  RESULT_UPLOAD_MESSAGE?: string;
  RESULT_SUCCESS_MESSAGE?: string;

  /* Feedback */
  FEEDBACK_CENTER_FACE?: string;
  FEEDBACK_FACE_NOT_FOUND?: string;
  FEEDBACK_FACE_NOT_LOOKING_STRAIGHT_AHEAD?: string;
  FEEDBACK_POSITION_FACE_STRAIGHT_IN_OVAL?: string;
  FEEDBACK_FACE_NOT_UPRIGHT?: string;
  FEEDBACK_HOLD_STEADY?: string;
  FEEDBACK_MOVE_PHONE_AWAY?: string;
  FEEDBACK_MOVE_PHONE_CLOSER?: string;
  FEEDBACK_MOVE_PHONE_TO_EYE_LEVEL?: string;
  FEEDBACK_USE_EVEN_LIGHTING?: string;
  FEEDBACK_FRAME_YOUR_FACE?: string;
  FEEDBACK_HOLD_STEADY_1?: string;
  FEEDBACK_HOLD_STEADY_2?: string;
  FEEDBACK_HOLD_STEADY_3?: string;
  FEEDBACK_REMOVE_DARK_GLASSES?: string;
  FEEDBACK_NEUTRAL_EXPRESSION?: string;
  FEEDBACK_CONDITIONS_TOO_BRIGHT?: string;
  FEEDBACK_BRIGHTEN_YOUR_ENVIRONMENT?: string;
};
