platform :ios, '12.4' 

source 'https://github.com/oititec/ios-artifactory.git'
source 'https://github.com/CocoaPods/Specs.git'
 

target 'RnLiveness3d' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for sampleUsageLivenessSDK
    pod 'OICommons', '~> 1.0.9'
    pod 'OINetwork', '~> 1.1.0'
    pod 'OIComponents', '1.2.0-beta'
    pod 'OILiveness3D', :git => 'https://github.com/oititec/ios-liveness-3d.git', :branch => 'feature/rn-loading-compatibility'
    pod 'OILiveness3D_FT', '9.6.33'
  
  end
