platform :ios, '12.4' 

source 'https://github.com/oititec/ios-artifactory.git'
source 'https://github.com/CocoaPods/Specs.git'
 

target 'RnLiveness3d' do
    use_frameworks!
    pod 'OILiveness3D', '3.16.0'
    # pod 'OILiveness3D_FT', git: 'https://github.com/oititec/ios-liveness3d-ft.git', branch: 'feature/31194-framework-update'
    # pod 'OILiveness3D', git: 'https://github.com/oititec/ios-liveness-3d.git', branch: 'chore/31198-facetec-update'
  
  end
